// test_helpers.c - Generated by claude.
#include "test_helpers.h"
#include <stdlib.h>
#include <string.h>
#include <criterion/criterion.h>




#define TEST_PRG_SIZE 0x8000 // 32KB, covers 0x8000-0xFFFF with no wraparound needed

// test_helpers.c
void make_test_system(TestSystem *sys) {
    memset(sys, 0, sizeof(TestSystem));

    sys->cartridge.prg_size = TEST_PRG_SIZE;
    sys->cartridge.prg_rom = calloc(sys->cartridge.prg_size, sizeof(uint8_t));

    sys->cartridge.chr_size = 0x2000;
    sys->cartridge.chr_rom = calloc(sys->cartridge.chr_size, sizeof(uint8_t));

    bus_init(&sys->bus, &sys->cartridge, &sys->ppu);

    sys->cartridge.prg_rom[RESET_VECTOR_ADDRESS_LOW - 0x8000] = 0x00;
    sys->cartridge.prg_rom[RESET_VECTOR_ADDRESS_HIGH - 0x8000] = 0x80; // PC = 0x8000

    cpu_init(&sys->cpu, &sys->bus);
}
void free_test_system(TestSystem *sys) {
    free(sys->cartridge.prg_rom);
    free(sys->cartridge.chr_rom);
}

void load_program(TestSystem *sys, uint16_t address, const uint8_t *program, size_t len) {
    // Writes directly to PRG ROM, bypassing bus_write.
    // address must be >= 0x8000 (current mapping start); adjust if mapper offset changes.
    uint32_t offset = address - 0x8000;
    memcpy(&sys->cartridge.prg_rom[offset], program, len);
}



void checkFlag(Cpu *cpu, int flag, int expected){

    cr_assert_eq(cpu->p & flag, expected,"expected flag value is %d but got %d", expected, cpu->p & flag);

    

}